#!/usr/bin/env python
from source.scraper import AdScraper
import asyncio

async def main():
    print(f"\033[92mStarting Scraper\033[0m")
    scraper = AdScraper()
    await scraper.scrapeAds()


if __name__ == "__main__":
    asyncio.run(main())
